### ISSUE TITLE
名为xxx.realm.lock的文件会被同步工具识别为xxx.realm编辑时产生的临时文件不予同步

### ISSUE THREAD

**Issue by TomoeMami** [Jugging/RoamOutliner#1]
希望能更换一个后缀名

**Comment by MarkMindCkm** [comment]
该文件无需同步，它确实是程序运行时产生的文件，只需要同步xxx.realm数据库文件即可

**Comment by TomoeMami** [comment]
> 该文件无需同步，它确实是程序运行时产生的文件，只需要同步xxx.realm数据库文件即可

利用坚果云同步时，A电脑上的改动无法在B电脑上查看，realm文件显示迟迟未更新。

下图是今日进行编辑之后的文件，可以看见lock文件及时更新但是realm文件迟迟未能更新，不知道数据保存到哪儿去了。

<img width="521" alt="Snipaste_2020-09-16_10-16-59" src="https://user-images.githubusercontent.com/16950305/93284753-e6dd2900-f805-11ea-8db5-24a7435e55af.png">

**Comment by MarkMindCkm** [comment]
确实是保存到数据库里，我在测试一下

**Comment by MarkMindCkm** [comment]
只有数据库文件大小变化才会同步

**Comment by MarkMindCkm** [comment]
> > 该文件无需同步，它确实是程序运行时产生的文件，只需要同步xxx.realm数据库文件即可
> 
> 利用坚果云同步时，A电脑上的改动无法在B电脑上查看，realm文件显示迟迟未更新。
> 
> 下图是今日进行编辑之后的文件，可以看见lock文件及时更新但是realm文件迟迟未能更新，不知道数据保存到哪儿去了。
> 
> <img alt="Snipaste_2020-09-16_10-16-59" width="521" src="https://user-images.githubusercontent.com/16950305/93284753-e6dd2900-f805-11ea-8db5-24a7435e55af.png">

是可以同步的，只有当数据库文件大小变化时才同步，因此实时性没有那么高

**Comment by TomoeMami** [comment]
> 是可以同步的，只有当数据库文件大小变化时才同步，因此实时性没有那么高

意思是只有写入了足够数据之后才会保存到本地吗？

能改为退出时即时保存吗。

**Comment by MarkMindCkm** [comment]
> > 是可以同步的，只有当数据库文件大小变化时才同步，因此实时性没有那么高
> 
> 意思是只有写入了足够数据之后才会保存到本地吗？
> 
> 能改为退出时即时保存吗。

测试时发现是写入的lock文件，然后累积到一定程度，会一次性合并入realm文件中，这个时候才会触发更新，这是数据库自身的行为，我在修改一下，看看能不能提高实时性

**Comment by TomoeMami** [comment]
在这个同步/保存问题修复好之前我都不太敢用来当主力软件

**Comment by MarkMindCkm** [comment]
> 在这个同步/保存问题修复好之前我都不太敢用来当主力软件

做了更详细的测试，发现实际上数据确实是存在realm中，在mac系统，每修改一步都可以触发同步，在window上不可以，只能手动替换数据库并重启软件，不过可以肯定的是 数据都是存在XXXX.realm中，因此不必担心数据丢失的情况

**Comment by TomoeMami** [comment]
> 做了更详细的测试，发现实际上数据确实是存在realm中，在mac系统，每修改一步都可以触发同步，在window上不可以，只能手动替换数据库并重启软件，不过可以肯定的是 数据都是存在XXXX.realm中，因此不必担心数据丢失的情况

意思是Windows上只能手动替换数据库才可以在两台设备之间保持同步吗

**Comment by MarkMindCkm** [comment]
> > 做了更详细的测试，发现实际上数据确实是存在realm中，在mac系统，每修改一步都可以触发同步，在window上不可以，只能手动替换数据库并重启软件，不过可以肯定的是 数据都是存在XXXX.realm中，因此不必担心数据丢失的情况
> 
> 意思是Windows上只能手动替换数据库才可以在两台设备之间保持同步吗

目前看来是这样，不知为什么window检测不到变化，这里我会一直关注
